ent2id:
  - "address"
  - "book"
  - "company"
  - "game"
  - "government"
  - "movie"
  - "name"
  - "organization"
  - "position"
  - "scene"

cawr_scheduler:
  "T_mult": 1
  "rewarm_epoch_num": 2

step_scheduler:
  "decay_rate": 0.999
  "decay_steps": 200

f1_save_threshold: 0.79
batch_size: 64
num_train_epoch: 50
max_len: 128
seed: 42
num_work_load: 4
learning_rate: 5e-5

train_data_path: "data/origin_data/global_point/"
pretrained_model_path: "model_weight/third_party_weights/bert_base_chinese/"
model_save_path: "./model_weights"
scheduler: "CAWR"